#YML file
#Employee Info
org: 
  nit: 
  #Simple Properties   
    e-id: 1234
    e-name: krishna
    e-sal: 30000
    #Collections
       #Array 
#   fav-food:
#    - Chicken Biriyani
#    - Mutton Biriyani
#    - Prawns Biriyani
        #or 
    fav-food: [Chicken Biriyani,Mutton Biriyani,Prawns Biriyani] 
    
       #List
#   fav-places:
#    - Maldives
#    - Dargeeling
#    - Switzerland
       #or
    fav-places: [Maldives,Dargeeling,Switzerland]
    
       #Set
#    phone-no:
#    - 9876543210
#    - 1234567890
#    - 8976543210
      #or
    phone-no: [9876543210,1234567890,8976543210]
     
       #Map
    id-details:
      aadhar: 365699903546
      voter: 678dbg78468
      pan: llikj5664r
      #Has-a Relastion
    company:
      c-id: 8976
      c-name: Intel
      c-address: Hyderabad